// Generated by https://quicktype.io

export interface Feature {
    properties?: Properties;
    text_es?: string;
    id?: string;
    place_type?: string[];
    geometry?: Geometry;
    place_name?: string;
    text?: string;
    relevance?: number;
    center?: number[];
    context?: Context[];
    bbox?: number[];
    place_name_es?: string;
    type?: string;
}

export interface Context {
    mapbox_id?: string;
    wikidata?: string;
    id?: string;
    text_es?: string;
    language_es?: string;
    short_code?: string;
    language?: string;
    text?: string;
}

export interface Geometry {
    coordinates: number[];
    type: string;
}

export interface Properties {
    mapbox_id: string;
    name?: string;
    descripcion?: string;
    urlImagen?: string;
}
